### ISSUE TITLE
session.create() issue / example

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#10]
I'm trying to make a simple `new` page for a model, but I cannot get `session.create()` to work. Not sure if I'm using epf wrongly, or if this is an issue. Code (in ember-script):

``` coffeescript
class App.FoosNewRoute extends Em.Route
  model: ->
    @session.newSession().create Foo.Task

  events:
    save: ->
      @context.session.flush()
```

Observation: calling `save` will only flush if `foos.new` route is entered directly from url. If I enter from, say, `foos.index` and `transitionTo` `foos.new`, now calling `save` will not flush anything (the promise is completed, but it does nothing). If I am in `foos.new` in the first place, then `transitionTo` another route away, and then goes back to `foos.new`, same observation (nothing flushed).

**Comment by jonnii** [comment]
I think this is because the model hook is only called if the route is entered from the url, if not the model should be known (because it's passed to the linkTo). I think something like this is better done in `activate`.

**Comment by heartsentwined** [comment]
Thanks for the `activate` idea. Clarification on the `model` hook:
- if it is a non-dynamic route (i.e. no `:foo_id` segments), then it is always called
- if it is a dynamic route, then it is only called on url entry; otherwise a model instance would be expected (from `transitionTo`, `replaceWith`, or the `linkTo` helper)

In this case though, the route in question is a non-dynamic route, so using the `model` hook should not be the cause.

**Comment by ghempton** [comment]
@heartsentwined I think you are correct about the behavior of the `model` hook. Is the model hook actually hit here?

Eventually I would like to document a solid set of example CRUD routes.

**Comment by heartsentwined** [comment]
I dropped `console.log()` statements in there, and have already checked that they are hit / not hit as described above.

**Comment by ghempton** [comment]
What exactly are the symptoms of flush not being called? I assume that the line of code is being hit but nothing is sent to the server? What happens if you create the model and manually set inside `setupController`? Also, if you have time to set up a fiddle for this I will debug this deeper.

**Comment by heartsentwined** [comment]
You're right, nothing is sent to the server. The flush is being called, and got resolved immediately. The above is a minimal illustration, a slightly longer example will be

``` coffee
# inside save event
@context.session.flush -> console.log 'done'
```

``` rb
# make server sleep, say, 2 secs, on any request
```

Now `flush()` does get called, and on the "successful" case described above, I see the server request in the console, and that `done` went back after 2 secs. On the "failure" case, no server request in the console, and `done` went back immediately. Quick and dirty testing, I admit.

The fiddle - sorry, I have no experience in making ember fiddles, and I have no idea how to illustrate this with one.

**Comment by ghempton** [comment]
Hmm sounds like for whatever reason the session is not seeing the newly created model as being dirty, or if it is, it could be being blocked by another operation on a different related model. Can you share more code (e.g. model definition)? Are there any other models being updated/created before you transition to this route?

**Comment by heartsentwined** [comment]
I'm fairly sure that's all useful code, nevertheless,

``` coffee
class App.Foo extends Ep.Model
  desc: Ep.attr 'string' # or whatever, just a dummy field
```

This has been isolated, there is no other model.

**Comment by ghempton** [comment]
Sorry, this one fell off the radar for me. Still stuck in the same place?

**Comment by rayb** [comment]
I will let you know shortly – thanks!

**Comment by rayb** [comment]
You can close this bug.  I don’t know what we did wrong before but it is no longer an issue.

Thanks

Ray

**Comment by heartsentwined** [comment]
I've been working on other code since this was reported; I'll get back on this when I'm back to epf code.

**Comment by heartsentwined** [comment]
No idea what happened, but as @rayb said, I can no longer reproduce this bug. Perhaps a blanket gem update somewhere during these days did it. Closing issue.
