### ISSUE TITLE
deserializeEmbeddedBelongsTo tries to createModel() with a string...

### ISSUE THREAD

**Issue by tobiaswerner** [getoutreach/epf#11]
I have problems deserializing embedded relationships. 

Up to now I could figure out that deserializeEmbeddedBelongsTo() which calls deserializeModel receives a string as type. 
deserializeModel() in turn tries to .create() the model but still fail (because it is typeof string).  

I configured the RestAdapter to always embed the one model in the other one..

``` javascript
Ep.RestAdapter.map('App.Gear', {
     user: { embedded: 'always' }
});
```

Did I miss some configuration?

**Comment by jasonkriss** [comment]
Can you post your model code for Gear and User?

**Comment by tobiaswerner** [comment]
Sure. Here it is...

``` javascript
var attr = Ep.attr,
    belongsTo = Ep.belongsTo,
    hasMany = Ep.hasMany;

App.Gear = Ep.Model.extend({
    user: belongsTo('App.User'),
        manufacturer: belongsTo('App.Manufacturer'),
    description: attr('string')
});
```

```
var attr = Ep.attr,
    belongsTo = Ep.belongsTo,
    hasMany = Ep.hasMany;

App.User = Ep.Model.extend({
  name: attr('string'),
  gears: hasMany('App.Gear')  
});
```

Nothing special so far, I think...
Thanks for your help in advance :)

**Comment by jasonkriss** [comment]
Without testing it out myself, I think is this is probably related to #4. EPF doesn't yet support defining relationships via strings, so try declaring your models like this:

``` javascript
App.Gear = Ep.Model.extend({
  description: attr('string')
});
App.Manufacturer = Ep.Model.extend({
  gears: hasMany(App.Gear)
});
App.User = Ep.Model.extend({
  name: attr(string),
  gears: hasMany(App.Gear)  
});
App.Gear.reopen({
  user: belongsTo(App.User),
  manufacturer: belongsTo(App.Manufacturer)
});
```

You need to use `reopen` whenever there is a circular dependency. Take a look at #4 though as this won't be necessary in the future.

**Comment by tobiaswerner** [comment]
Perfect, many thanks for your explanation. 
Will try it tomorrow...

**Comment by ghempton** [comment]
I think @jasonkriss is correct. I will try and get #4 fixed soon. I'm going to close this for now, feel free to reopen if that isn't the fix.

**Comment by tobiaswerner** [comment]
Your hints solved my problem. Many thanks :+1:
