### ISSUE TITLE
Attempting to register an unknown factory: `store:main`

### ISSUE THREAD

**Issue by Manumie** [getoutreach/epf#113]
Hello,
I'm trying to use EPF in an Ember App Kit project.
I removed the call to Ember Data in index.html and replaced it with: 

```
<script src="/vendor/epf/dist/epf.js"></script>
```

I'm starting from a blank EAK project, so I haven't defined any model yet.

When I run `grunt server` and connect to `localhost:8000`, I get the debug info just fine, showing that EPF si loaded

```
DEBUG -----------------------------
Ember      : 1.2.0
Handlebars : 1.1.2
jQuery     : 1.9.1
EPF        : 0.1.3
DEBUG -----------------------------
```

But then I get this error:

```
Uncaught TypeError: Attempting to register an unknown factory: `store:main` 
```

And the app won't start.

What am I doing wrong ?

**Comment by ghempton** [comment]
That looks like an old version of epf. I recently added the `dist` folder to the repo so that it plays more nicely with bower. Update epf via: `bower install --save epf=git@github.com:GroupTalent/epf.git#master`

**Comment by Manumie** [comment]
That was it.
Thanks a lot !

I'll probably be asking you more questions as I need to write an adapter so that EPF can connect to a socket (powered by socket.io) instead of a REST API.

**Comment by cellis** [comment]
Could you guys bump the version on www.epf.io to 0.1.4 for those that don't want to live on the edge ? I ran into this issue too.

**Comment by tamebadger** [comment]
Just a reminder.. would also really appreciate if you could bump ^ the version, there will likely be other guys coming along the same path, using old school download button on the www.epf.io site

**Comment by drkmen** [comment]
+1
