### ISSUE TITLE
Calling undefined method "stringify" on adapter during session.flush

### ISSUE THREAD

**Issue by Akii** [getoutreach/epf#114]
Hi,

I am still pretty new to both, ember and EPF. I tried out ember-data first then wanted to give EPF a try.

All went well until I wanted to persist a newly created model. In line 2047 the undefined method stringify is called on the adapter. Correcting the line to this seems to work: <pre>hash.data = JSON.stringify(hash.data);</pre>

No idea if this is a bug, and if so, where it comes from (someone should have noticed it by now, right?). Anyhow, hope it helps.

**Comment by ghempton** [comment]
Whoa, not sure how that one made it through. I need to switch to sinon instead of the test adapter I am using (as this particular line is not covered).

Anyways, I just corrected the issue. Try using the latest from master :).

**Comment by Akii** [comment]
Thanks for the fast fix. Works like a charm, as does the rest of EPF :)
