### ISSUE TITLE
App.Adapter.map doesn't work

### ISSUE THREAD

**Issue by artdavalos** [getoutreach/epf#118]
Hello I have a problem with App.Adapter.map, my code is

App.Adapter = Ep.RestAdapter.extend({
    namespace: 'sir/action/rest'
    });

App.Adapter.map('App.TipoTramite', {
    primaryKey: 'idTipoTramite'
  });

App.TipoTramite = Ep.Model.extend({
    idTipoTramite: Ep.attr('number'),
    descripcion: Ep.attr('string'),
    agregable: Ep.attr('string'),
    descripcionCorta: Ep.attr('string'),
});

But when I started the application it show me : 

Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi) 
DEBUG: ------------------------------- ember.js:3496
DEBUG: Ember      : 1.5.0-beta.1+canary.338537bd ember.js:3496
DEBUG: Handlebars : 1.3.0 ember.js:3496
DEBUG: jQuery     : 1.10.2 ember.js:3496
DEBUG: EPF        : 0.1.4 ember.js:3496
DEBUG: ------------------------------- ember.js:3496
Uncaught TypeError: Object function () {
    if (!wasApplied) {
      Class.proto(); // prepare prototype...
    }
    o_defineProperty(this, GUID_KEY, nullDescriptor);
    o_defineProperty(this, '__nextSuper', undefinedDescriptor);
    var m = met...<omitted>...p' 

I hope someone can help me.

Thanks in advance.

**Comment by ghempton** [comment]
What documentation did you reference for using `.map`? This API has changed and you can now do this by creating a custom serializer:

```
App.TipoTramiteSerializer = Ep.Serializer.extend({
  properties: {
    id: {key: 'idTipoTramite'}
  }
}
```
