### ISSUE TITLE
Updating sideloaded hasMany relationship on flush

### ISSUE THREAD

**Issue by benperiton** [getoutreach/epf#121]
Is it possible to have relationships updated when flushing changes?
For example, if I have an auditing service on the backend that adds a line whenever something changes, can i have these updated when the save is successful?

Example response:

``` javascript
{
product: {
    id: 12,
    name: 'Widget',
    audit_ids: [1,2]
},
audits: [
    {id: 1, timestamp: '12/2/13'},
    {id: 2, timestamp: '12/2/14'}
]
}
```

The product model seems to update, but the audits relationship doesn't update. (These are sideloaded at the beginning - which works fine)

**Comment by ghempton** [comment]
Yes, they should definitely update. Can you post more of your code?

**Comment by benperiton** [comment]
Ah OK, I wasn't sure if it was supported or not. I'll have a play and see what I'm doing wrong.

If I still have no joy I'll chuck some code up.

Thanks!

**Comment by benperiton** [comment]
So it seems I broke the api at some point yesterday, long day! 

Sorry to have troubled you, I'll close this!
