### ISSUE TITLE
typeKey seems incompatible with non-global Ember

### ISSUE THREAD

**Issue by machty** [getoutreach/epf#125]
https://github.com/getoutreach/epf/blob/master/lib/model/model.js#L184

This line of code seems hardwired to expect something like `App.ModelName`, whereas EAK and ember-cli use the ember-resolver that produces something looking like

```
"retailer-admin@model:inbox-item:"
```

see here: https://github.com/stefanpenner/ember-jj-abrams-resolver/blob/master/packages/ember-resolver/lib/core.js#L220

Not sure the right way to go here; Ember Data seems hardwired to do `typeKey = normalizedKey.split(':', 2)[1];`, so not sure how that works with global Ember apps.

**Comment by ghempton** [comment]
I think we should just keep these types of conventions in line with Ember Data (which this original code was actually taken from as well).

In the mean time, this can easily be resolved in any app by explicitly defining `typeKey`:

```
var Post = Ep.Model.extend({
  typeKey: 'post'
});
```
