### ISSUE TITLE
Still Alive?

### ISSUE THREAD

**Issue by dev-inigmas** [getoutreach/epf#139]
Quick question... Is EPF still alive?

I'm asking because the Discussion Group is so completely lacking in activity and the documentation regarding the differences between Ember Data and EPF are very out of date.

Because Ember Data completely stopped supporting embedded documents, I can't really use it anymore. EPF seems like a great place to go... I'd just like to make sure you someone is sticking with this project for the long haul.

Thanks.

**Comment by ghempton** [comment]
@dlpatri EPF is very much alive. We use it in production on getoutreach.com.

The documents are terribly outdated– need to find time to update them.

**Comment by dev-inigmas** [comment]
Thanks for the quick response. It's good to know that EPF is still alive and well.
