### ISSUE TITLE
Checking if model is dirty

### ISSUE THREAD

**Issue by denisnazarov** [getoutreach/epf#17]
How do I check if a model is dirty? I am trying to see if a model in a child session is dirty by doing something like `model.isDirty` or `model.get('isDirty')` which is returning undefined. The only way I can check is by doing `model.session.get("dirtyModels").contains(model)` which feels wrong and I am trying to observe the isDirty property like I did in ember-data. 

Thanks for making epf!

**Comment by ghempton** [comment]
I am planning on adding an `isDirty` property :).

**Comment by ghempton** [comment]
This should be fixed in master. Model now has an `isDirty` property.
