### ISSUE TITLE
inject models from known json

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#18]
Use case: pre-load static model data from embedded json in js files.

Ember-data version

``` coffee
class App.Store extends DS.Store
  init: ->
    super.apply this, arguments
    @loadMany(App.Foo, '[{"id":1, "value":"a"}, {"id":2, "value":"b"}]')
```

Epf equivalent = ?

**Comment by heartsentwined** [comment]
I saw `session.merge()`, but I'm not sure if that's the equivalent. The method signature

``` javascript
  /**
    @param {Ep.Model} model The model to merge
    @param {Ep.MergeStrategy} [strategy] The merge strategy to use
  */
```

seems to expect a model instance. Unless the epf idiom is to create each individual models from the json manually, and then load them?

**Comment by ghempton** [comment]
In epf, unlike ED, you can actually freely create models using normal `create`. In the above case you could simply do:

``` javascript
session.merge(App.Foo.create({"id":1, "value":"a"}));
```

In our app, we actually preload models serialized by AMS (which may contain sideloads etc.). In this case you have to go through the adapter. Eventually I want to add a cleaner api around this.

**Comment by heartsentwined** [comment]
We have the same AMS use case too, the original code was actually

``` coffee
class App.Store extends DS.Store
  init: ->
    super.apply this, arguments
    @loadMany(App.Foo, \
    <%= ActiveModel::ArraySerializer.new(Foo.all).as_json.to_json %>)
```

but I have stripped out that part for being not an epf concern.

Would you mind posting your epf example for this?

**Comment by heartsentwined** [comment]
One more question: 

What would be the state of the new model if I do this?

``` javascript
session.merge(App.Foo.create({"id":1, "value":"a"}));
```

\- or in other words, if I `flush()` the session afterwards, would it try to save a "new" model to the server?

**Comment by ghempton** [comment]
I am actually surprised that works for you. Last I checked you had to go through the adapter in ED as well to accomplish this.

Here is a stripped down version of our code:

``` coffeescript
# Preload models
App.initializer
  name: 'preload_models'

  initialize: (container, application) ->
    adapter = container.lookup('adapter:main')
    session = container.lookup('session:main')
    models = adapter.didReceiveDataForFind(ENV['preload'], type)
    models.forEach (model) -> session.merge(model)
```

Could be prettier :/

**Comment by ghempton** [comment]
Re: your second question: merge is only meant to merge in new data that has come from the server. In the above case it would not go to the server.

**Comment by ghempton** [comment]
btw @heartsentwined , feel free to add me ghempton@gmail.com if you ever want to IM.

**Comment by heartsentwined** [comment]
Thanks for the sample, so it's 

``` coffee
adapter.didReceiveDataForFind('[{"id":1, "value":"a"}, {"id":2, "value":"b"}]', App.Foo)
# first arg json string
# second arg model class
```

right?

**Comment by ghempton** [comment]
Ah it actually expects only a single serialized model, not an array. For now I think you will have to iterate over the array. E.g.

```
[{"id":1, "value":"a"}, {"id":2, "value":"b"}]'.forEach (json) -> adapter.didReceiveDataForFind(json, App.Foo)
```

**Comment by ghempton** [comment]
Actually nm, I take that back :P. It should work with an array. Sorry about the confusion.

**Comment by heartsentwined** [comment]
Thanks a lot for the clarifications! I'll test that out and reopen this if it doesn't work.

\- and thanks for the IM invite too!

**Comment by heartsentwined** [comment]
Gotcha for anyone coming across this usecase: the above code sample does not work - I have to wrap the json in its root key.

``` javascript
json = '[{"id":1, "value":"a"}, {"id":2, "value":"b"}]'
adapter.didReceiveDataForFind(json, App.Foo) // no

json = '{ foos: [{"id":1, "value":"a"}, {"id":2, "value":"b"}] }'
adapter.didReceiveDataForFind(json, App.Foo) // okay now
```
