### ISSUE TITLE
How to configure the adapter?

### ISSUE THREAD

**Issue by gerry3** [getoutreach/epf#19]
We are trying to migrate from ember-data to epf. In ember-data we would configure our store's adapter with a url and namespace.

How can I configure the url and namespace of the epf adapter?

Also, maybe this should be added to the migration guide (http://epf.io/migrating_from_ember_data.html).

**Comment by ghempton** [comment]
This should work the same as in Ember Data:

``` javascript
App.Adapter = Ep.RestAdapter.extend({
  namespace: 'api'
});
```

**Comment by rayb** [comment]
Thanks  - got a nice api layer going now.

Also, I was wondering if we can could get access to the slide decks and or video/ audio of the presentations from last nights meetup.  I would like to share them with my intern.

Ray

**Comment by ghempton** [comment]
@rayb I will post both of those tonight

**Comment by ghempton** [comment]
I am going to close this issue, let me know if you have any other questions on adapter configuration.

**Comment by Emerson** [comment]
Hate to reopen this, but I've been trying to figure this out for awhile without any luck.

My app is divided into two sections, admin and standard user. I'd like all the admin api requests to be namespaced differently than my standard user requests. Any suggestions on the best way of doing this? Should I be changing the namespace depending on the route, or creating an entirely new adapter just for the admin section...

Any suggestions would be really appreciated
