### ISSUE TITLE
Flushing child session merges child model with parent model even if PUT request failed

### ISSUE THREAD

**Issue by denisnazarov** [getoutreach/epf#22]
I am following the following convention from the docs:

``` javascript
var post = session.load(App.Post, 1);

var childSession = session.newSession(); // this creates a "child" session

var childPost = childSession.load(App.Post, 1); // this record instance is separate from its corresponding instance in the parent session

post === childPost; // returns false, they are separate instances
post.isEqual(childPost); // this will return true

childPost.title = 'something'; // this will not affect `post`

childSession.flush(); // this will flush changes both to the backend and the parent session, at this point `post` will have its title updated to reflect `childPost`
```

If the PUT request fails after doing childSession.flush(), post is still updated to match the changes to childPost. 

I am using a child session to update a model (it is a user settings page) so it doesn't change in real time in another part of the UI. This is very easy using child sessions and child models (compared to ember-data), but the changes shouldn't merge if the backend PUT fails.

Any workarounds?

**Comment by ghempton** [comment]
Good find, this should definitely not be the case. I am planning on a big code spike on epf this weekend and will fix this.

For the short term as a workaround, you could "rollback" the parent session's record. This would mean something like the following:

``` javascript
var model = ...
var shadow = session.getShadow(model);
shadow.copyAttributes(model);
// here the model will be in its original state before the child session flushed
```

**Comment by ghempton** [comment]
The semantics here have changed and should address this. See https://github.com/GroupTalent/epf/issues/59.
