### ISSUE TITLE
Consistent id-to-string coercion

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#27]
From #7 at [comment](https://github.com/GroupTalent/epf/issues/7#issuecomment-21417893): 

``` javascript
// works
session.merge(App.Post.create({id: '1', title: 'testing'}));

// doesn't work
session.merge(App.Post.create({id: 1, title: 'testing'}));
```

Numeric `id` should also be accepted. The current behavior doesn't parallel

``` javascript
session.load(App.Post, 1); // works with numeric argument!
```

The behind-the-scenes coercion of `id` to `string` could be consistently applied everywhere. Perhaps a full code-review needed to search for _all_ such cases.

**Comment by ghempton** [comment]
This should be much more consist. See `serializers/id_serializer.js`.
