### ISSUE TITLE
How to extend serializer and deserializer.

### ISSUE THREAD

**Issue by hashg** [getoutreach/epf#30]
My json structure does not confirm with the Ember Data or epf format.
Plurals json is

```
{
  "total_pages": 1,
  "objects": [
    {
     "id" : "1",
     "name": "name1",
     "child" : []
    },
    {
     "id" : "2",
     "name": "name2",
     "child" : []
    }
   ]
}  
```

Singular json is

```
{
  "id" : "1",
  "name": "name1",
  "child" : []
}
```

**Comment by ghempton** [comment]
Will come up with a detailed response to this once I have some free time.

**Comment by taras** [comment]
@hashg I'm doing something similar for deployd package. What you want to do is pretty straightforward, you just need to modify the data that's being sent to and received from the service. You can see my gist https://gist.github.com/taras/87c3c112ed5a2b17d791

Most of the work for you will in be didReceiveDataForFind, didReceiveDataForLoad & didReceiveData

**Comment by hashg** [comment]
@taras Thank you. I'll take a look at it.

**Comment by ghempton** [comment]
The serialization layer is much more simple now. In order to create a custom serializer for a model do something like the following:

```
App.PostSerializer = Ep.Serializer.extend({
  deserialize: function(data) {
  },

  serialize: function(data) {
  }
});

```
