### ISSUE TITLE
Model with name ending with "s" not properly retrieved

### ISSUE THREAD

**Issue by c0urg3tt3** [getoutreach/epf#36]
Hi, i'm currently using epf with a lot of models and face a strange bug,

if i have a company and companyHasAddress models

``` javascript
Ep.RestAdapter.configure('App.Company', {
  sideloadsAs: 'companies'
});

Ep.RestAdapter.configure('App.CompanyHasAddress', {
  sideloadsAs: 'company_has_addresses'
});

Ep.RestAdapter.configure('plurals', {    
    company: 'companies',
    company_has_address: 'company_has_addresses'
});

App.Adapter = Ep.RestAdapter.extend({
    namespace: 'api'
});

App.Company = Ep.Model();
App.CompanyHasAddress = Ep.Model();

App.Company.reopen({
  companyHasAddresses: Ep.hasMany(App.CompanyHasAddress, {inverse: 'company'})
});

App.CompanyHasAddress.reopen({
  company: Ep.belongsTo(App.Company)
});
```

in my route i ve got an event that handle the creating process for a companyHasAddress

``` javascript
createAddress: function(newAddress) {
  var session, childSession, company, companyHasAddress, flashMessenger;
  session = this.session;
  childSession = session.newSession(); 
  company = this.controller.get('model');
  companyHasAddress = childSession.create(App.CompanyHasAddress, newAddress);
  childSession.flush().then(function(models) {
    company.get('companyHasAddresses').pushObject(companyHasAddress);
  }, function(errors) {
    var xhr = companyHasAddress.get('errors.xhr');
  });
}
```

epf is looking for company_has_addresses hash key, 

```
 { "company_has_addresses": { ... address data }}
```

but theorically the expected response should be 

```
 { "company_has_address": { ... address data }}
```

if i return the expected `company_has_address` hash key error show up has the hash key as no corresponding mapping,
if i return the expected `company_has_addresses` hash key `then` method is never firered probably cause `company_has_address` hash key is expected for a post to resolve or reject the promise.

i will look at the test of epf to see if i am able to produce some for demonstrate the issue.

ps: i m not returning the clientID from the server, i use the proposed patch at issue https://github.com/GroupTalent/epf/issues/23 

ps²: i m not sure it s an epf or an ember-data issue

**Comment by c0urg3tt3** [comment]
ok i think i understand what is happening,
when singularize is executed, no plural value is matching,
so `singularize` is looking for an ending "s" char and substring it from the passed name.
resulting in something like `CompanyHasAddres`.
a quick fix is simply return the `name` from `singularize`, 
and everything work has expected.

``` javascript
singularize: function (name) {
  var plurals = this.configurations.get('plurals');
  if (plurals) {
    for (var i in plurals) 
      if (plurals[i] === name) {{
        return i;
      }
    }
  }
/* 
  if (name.lastIndexOf('s') === name.length - 1) {
    return name.substring(0, name.length - 1);
  } else {
    return name;
  } 
*/
  return name;
}
```

**Comment by jasonkriss** [comment]
That may solve your problem but why aren't there any plurals registered? Calling `this.configurations.get('plurals')` should return the configured hash from above. Are you saying that `this.configurations.get('plurals')` returns undefined?

**Comment by c0urg3tt3** [comment]
nope plurals are defined,
but name passed by epf on deserialization to singularize is the singular value,
plurals are looped t determine if the plural name match the name to singularize,
but none are found, cause singular name is different than plural name,
so the next step is to looking for an ending "s" char, and assume that he have to be truncate to give the singular name,
or no "s" char spotted and the name is returned as it ...

in my case i have some model with ending "s" char for singular name, like `address`,
if i declare a plural as `addresses` when i create an `address`, the expected hash key is `address` but for the previous described scenario the retrieved singular name will be `addres` 

two solutions that i tested.
looking in the plurals loop if plural key equal name
before looking if plural value equal name

``` javascript
singularize: function (name) {
    var plurals = this.configurations.get('plurals');
    console.log(plurals);
    if (plurals) {
        for (var i in plurals) {
            if (i === name) {
                return i;
            } else if (plurals[i] === name) {
                return i;
            }
        }
    }

    if (name.lastIndexOf('s') === name.length - 1) {
        return name.substring(0, name.length - 1);
    } 
    return name;
}
```

or after the plurals loop, testing if `name` ending with two "s"

``` javascript
singularize: function (name) {
    var plurals = this.configurations.get('plurals');
    console.log(plurals);
    if (plurals) {
        for (var i in plurals) {
            if (plurals[i] === name) {
                return i;
            }
        }
    }
    if (/ss$/.test(name)) {
        return name;
    } 
    if (name.lastIndexOf('s') === name.length - 1) {
        return name.substring(0, name.length - 1);
    } 
    return name;
}
```

**Comment by ghempton** [comment]
I don't have a solid answer for you right now as I need to take a big pass on the serialization layer. Most of the serialization logic is currently based directly off of Ember Data. Soon I would like to add a real inflector to the code to resolve this.

**Comment by jasonkriss** [comment]
I guess I still don't really understand the problem. This doesn't seem to be an issue with `singularize`. It is behaving correctly as it assumes that it is passed a pluralized name. The issue seems to be happening earlier. Why is epf looking for a `company_has_addresses` key in the payload when you are creating a single record? Can you confirm that the adapter's create method is called correctly and that your server is receiving the expected json: e.g. 

``` javascript
{ company_has_address: {...} }
```

**Comment by c0urg3tt3** [comment]
yes, currenty i ve got a full CRUD working with something like 30 models more,
the request response are well formatted,
and properly handled by my app,

> Why is epf looking for a company_has_addresses key in the payload when you are creating a single record?

because he don't find any matching key has `company_has_addresses` either has `company_has_adres`,
the first one is for pluralized response, the second is the result of the singularize that don t found matching plural as it expect to be just an appended "s" char at the end of the singularized name ...

i think it s because ED and epf allow to lazily declare singular that are derived from the plural form of a model, a quick way will be to have the ability to declare both plurals and singulars, and then in the singularize looking first for a declared singular for the name, or for a singularized plural or for an ending "s" char or returning as it ...

**Comment by ghempton** [comment]
The serialization layer has changed considerably since this issue was created. Going to close.
