### ISSUE TITLE
Defining relationships with strings

### ISSUE THREAD

**Issue by mitchlloyd** [getoutreach/epf#4]
I noticed that your examples define relationships by passing the actual model classes as arguments.

```
App.Post = Ep.Model.extend({
  comments: Ep.hasMany(App.Comment),
  user: Ep.belongsTo(App.User)
});
```

This is different than the Ember Data examples that define relationships with strings like this.

```
App.Post = DS.Model.extend({
  comments: DS.hasMany('App.Comment'),
  user: DS.belongsTo('App.User')
});
```

Can relationships be created using strings to represent the related models?

**Comment by ghempton** [comment]
String support is coming soon, but it will be a slightly different flavor than Ember Data. Epf will use container strings:

``` javascript
App.Post = Ep.Model.extend({
  comments: Ep.hasMany('comment'),
  user: Ep.belongsTo('user')
});
```

This already works with sessions. E.g. `session.load('post', 1)`, but not quite yet with relationships. To work around this in the short term you should reopen the class when you have circular dependencies:

``` javascript
App.Post = Ep.Model.extend();
App.Comment = Ep.Model.extend({
  post: Ep.belongsTo(App.Post)
});
App.Post.reopen({
  comments: Ep.hasMany(App.Comment)
});
```

Hope this helps.

**Comment by mitchlloyd** [comment]
Thanks for the workaround.  I'm really excited to try Epf out!

**Comment by ghempton** [comment]
This should work now. E.g. `Ep.belongsTo('post')` or `Ep.hasMany('comment')`. A common typo might be to use the plural for Ep.hasMany, but the singular should always be used for the time being.

**Comment by lastobelus** [comment]
camel case or underscore?

**Comment by ghempton** [comment]
It follows the same naming conventions as ember proper. I think it normalizes both camel case and underscore.
