### ISSUE TITLE
Query data not resolving correctly

### ISSUE THREAD

**Issue by ginty** [getoutreach/epf#42]
Hi,

I've turned this bit of ED code:

``` coffeescript
controller.set("content", App.User.find(type: "staff"))
```

into this EPF code:

``` coffeescript
controller.set("content", @session.query(App.User, type: "staff"))
```

The correct request is fired off and from stepping through the code execution I can see that the models get loaded in to an array correctly.

However the <code>@session.query</code> method ends up returning a promise and Ember does not like it, it leads to some obscure errors like:

```
Uncaught TypeError: Object [object Object] has no method 'slice' 
```

which occur when Ember is trying to sort the content.

Is there anything wrong with my code?

Thanks!

**Comment by ghempton** [comment]
The issue here is that epf is returning a pure promise, whereas ED returns an array that is also a promise (this is bad IMO). A good place to set the controller's content is at the route layer:

``` javascript
App.StaffRoute = Ember.Route.extend({
  // the router waits for promises to resolve so the controller will get the resolution of this promise and it will have the desired behavior
  model: function() {
     return this.session.query(App.User, type: "staff");
  }
});
```

If you want to do this outside of the router, then you should do it in the promise callback:

``` javascript
 @session.query(App.User, type: "staff").then (arr) -> controller.set('content', arr)
```

**Comment by ginty** [comment]
Perfect, thanks!
