### ISSUE TITLE
Include build result in repository

### ISSUE THREAD

**Issue by iamklob** [getoutreach/epf#43]
or add a shim to github.com/components org.

It would be nice to be able to add epf as bower dependency and as I've learned (e.g. http://stackoverflow.com/a/17178150/973047) the preferred way for bower and components is to have built library in the repository.

**Comment by ghempton** [comment]
I'm torn on this... I would like to see bower support, but having generated files checked into version control feels messy. Is this really the best practice?

**Comment by iamklob** [comment]
I'm also not a big fan of having anything which can be generated from source checked into repo but apparently this is the way bower expects things to be. That's IMHO the reason for github.com/component - ember.js has same build strategy as epf as you probably know and so it's there for bower.

Maybe a solution would be having commit hook on epf publishing distribution file to some (not yet existing) repo after creating version tag in epf's repo?

**Comment by taras** [comment]
What about doing what Ember Data & Ember Model which is to generate builds that can be used by specifying the url of the file in brower.js?

**For example:**

``` json

{
  "name": "app",
  "version": "0.1.0",
  "dependencies": {
    "jquery": "~1.9.1",
    "jquery-ui": "~1.9",
    "handlebars": "1.0.0-rc.4",
    "ember": "~1.0.0",
    "ember-model": "http://builds.erikbryn.com/ember-model/ember-model-latest.js", // <-- path to the built file
    "bootstrap":"2.3.2"
  },
  "devDependencies": {
    "ember-mocha-adapter": "0.1.1"
  }
}


```

**Comment by ghempton** [comment]
Would definitely like bower support. Would anyone like to take a crack at this? I can help by establishing a reliable builds location (releases are currently zipped). I am not particular to any of the solutions (but would prefer no checking in the build to the repo).

**Comment by taras** [comment]
I could take a crack at this early next week. 

I'm going to do some research on bower and describes some options before I move forward.

**Comment by ghempton** [comment]
I have decided to relent and just include the build result in the repo. Life is too short to fight bower.
