### ISSUE TITLE
A simple working example

### ISSUE THREAD

**Issue by zooshme** [getoutreach/epf#46]
Hi,

Could you please post a simple working example of how to integrate EPF with Ember.js

Thanks.

**Comment by rayb** [comment]
Hi,

Here is one simple example for ember-data converters coming over to epf, showing full CRUD parent/child relationships:

https://github.com/rayb/epf_skeleton

It is by no means endorsed by Gordon, but it did benefit from his direct input.

Ray Bunnage

**Comment by zooshme** [comment]
Thank you @rayb. Much appreciated.

**Comment by kiwiupover** [comment]
I just pushed [epf_example](https://github.com/kiwiupover/epf_example) app that is a port of the ember_data_example. Let me know if it is helpful.
