### ISSUE TITLE
Manually loading external data

### ISSUE THREAD

**Issue by sapientpants** [getoutreach/epf#47]
The example of loading data in the Ember.js Persistence Foundation video (20:10) shows the code below for loading AJAX retrieved data into the session.

```
$.getJSON('/users/1', function(data) {
  var user = App.User.create(data);
  session.merge(user);
});
```

Unfortunately this won't work as expected if any of the attributes of App.User are not strings.

I'm currently working around this using the code below.

```
$.getJSON('/users/1', function(data) {
  var user = session.get('adapter.serializer').deserializeModel(App.User, data);
  session.merge(user);
});
```

While this works for deserializing the attributes properly, it seems messy to have to reach into the session.

I've started experimenting with having `session.create()` use the deserializer, but I'm not sure if this is the best approach.

**Comment by jasonkriss** [comment]
Take a look at #18. It sounds like there is a plan for a cleaner/dedicated API for this. It definitely seems to be a common need. Although, I'm not sure how you could ever do this without going through the adapter/serializer layer if you want to keep things properly encapsulated.

**Comment by ghempton** [comment]
#48 is also relevant.

**Comment by denisnazarov** [comment]
@ghempton How would one merge AJAX retrieved data into an existing model without doing it by hand? The JSON has ids that match already existing models on the client, but the rest of the data is modified and needs to be merged. As I understand `session.merge(model)` only works if you pass in a newly created model.

**Comment by ghempton** [comment]
Session.merge should be the correct way. Is that not working?

**Comment by denisnazarov** [comment]
It works if the model you pass to `session.merge` is one you just newly created. What if the JSON you have loaded manually is for an existing model in the session? Updating it the model's attributes from that data will dirty it, and flushing afterwards will try to persist it, whereas you want it to just update and be clean.

**Comment by denisnazarov** [comment]
What I am trying to do is working here: http://jsfiddle.net/NQKvy/61/

But in my more complex implementation it fails with the following error:

```
Uncaught TypeError: Cannot call method 'toString' of undefined epf.js?body=1:2796
Ep.Adapter.Ember.Object.extend._typeToString epf.js?body=1:2796
Ep.Adapter.Ember.Object.extend._generateClientId epf.js?body=1:2793
Ep.Adapter.Ember.Object.extend.reifyClientId epf.js?body=1:2781
Ep.Session.Ember.Object.extend.reifyClientId epf.js?body=1:3353
Ep.Session.reopen.merge epf.js?body=1:3011
(anonymous function) epf.js?body=1:3482
Ember.Enumerable.Ember.Mixin.create.forEach ember.js?body=1:8479
(anonymous function) epf.js?body=1:3477
(anonymous function) epf.js?body=1:1172
(anonymous function) ember.js?body=1:2723
OrderedSet.forEach ember.js?body=1:2566
Map.forEach ember.js?body=1:2721
Ep.Model.reopenClass.eachRelationship epf.js?body=1:1171
Ep.Model.reopen.eachRelationship epf.js?body=1:1183
Ep.PerField.Ep.MergeStrategy.extend.mergeRelationships epf.js?body=1:3461
Ep.PerField.Ep.MergeStrategy.extend.merge epf.js?body=1:3443
superWrapper ember.js?body=1:917
Ep.Session.reopen._mergeModel epf.js?body=1:3100
(anonymous function) epf.js?body=1:3030
Ep.Session.Ember.Object.extend.suspendDirtyChecking epf.js?body=1:3401
Ep.Session.reopen._mergeSuccess epf.js?body=1:3029
Ep.Session.reopen.merge epf.js?body=1:3015
(anonymous function) tests_route.js?body=1:76
fire jquery.js?body=1:3075
self.fireWith jquery.js?body=1:3187
done jquery.js?body=1:8254
callback
```

Some of my attributes are also not strings like @pansapien.

EDIT: I had a bug where my id keys were different (id and _id), and changing that makes the models merge correctly for simple models. In my case my model has side loaded hasMany data, and here making a new model and passing an array of ids of my sideloaded models does nothing. Ex: Passing item_ids with an array of ids, and then trying to do `model.get('items')` after merging results in an empty array.

**Comment by ghempton** [comment]
I have recently added `session.mergeData(data, type)` which should solve this use case.
