### ISSUE TITLE
Creating a custom adapter or adapter for deployd

### ISSUE THREAD

**Issue by taras** [getoutreach/epf#48]
deployd.com is a tool that provides RESTful APIs for custom models. I'd like to use it but has a slightly different API layout than Ember Data expects. For example, the returned JSON is not wrapped in hash, ie:

``` json
[
{ "id": "30", "name": "Hello World!" }
]
```

Not

``` json
{ 
    "items": [
        { "id": 30, "name": "Hello World!" } 
   ]
}
```

Are there any considerations for this in EPF? anything in particular that is relevant to building a custom adapter for this kind of an API?

**Comment by taras** [comment]
I started to do and its pretty easy to do so far. You can see this Gist https://gist.github.com/taras/87c3c112ed5a2b17d791

I haven't done relationships yet, but basic CRUD functionality is working. Most of the work is removing and adding type wrapper around the payload. 

One thing to note, I had to copy create & update functions because I couldn't modify the data that was used to make a request. It would be clearer to handle that via a callback ( possibly to the serializer )

**Comment by ghempton** [comment]
I'm glad you got somewhere with this! Another way to do this would be to move a lot of this logic into your custom serializer. At a high level, `serializer.deserialize` should just returns a collection of models and you can create those models however you want based off of the JSON. You can also set `isDeleted` and `errors` to indicate more than just loading.

Someday I will get around to cleaning up/documenting the serializer API.

**Comment by taras** [comment]
I realized that I can use serializer.deserialize about half way through it. I'm going to keep working on this and if I use it long enough then I'll turn it into a module that others will be able to use. 

Thank you for EPF, its a pleasure to work with.
