### ISSUE TITLE
Can it be used without Emberjs

### ISSUE THREAD

**Issue by samarjit** [getoutreach/epf#56]
I have been looking for a generic javascript datasource framework much of what EPF does. basically I was looking for 
1. defining models 
2. datatype defined for each attribute
3. Conversion from server string to formatted output currency/dates/numbers
4. Serialization of formatted strings back to model attribute datatype
5. model list
6. Sorting of model list/serverside
7. filtering of model list/serverside
8. child parent relationships
9. observable models and lists
10. Pagination support 

So that this datasource can be used by GUI components like tree grids and comboboxes autocompletes dynamic forms etc.

**Comment by ghempton** [comment]
Theoretically you can use epf with just `ember-runtime` which just includes things like the core Ember.js object model (it doesn't include the application layer/router/views/handlebars etc.). This will trim down the footprint and _might_ work outside of an Ember.js application. I am not going to official endorse this and would recommend using epf in conjunction with Ember.js, but I would be interested to see where it went.
