### ISSUE TITLE
Documentation on Usage

### ISSUE THREAD

**Issue by brandonparsons** [getoutreach/epf#57]
Hi there,

I like the sound of EPF, but I'm a bit confused by the docs.  For example, where/how do I specify the URL endpoint of the REST backend?  The equivalent of `ember-data` :

```
  App.Store = DS.Store.extend
    adapter: DS.RESTAdapter.create
      url: '/api/v1'
```

Maybe inclusion of a super-simple example might help?

**Comment by c0urg3tt3** [comment]
``` javascript
App.Adapter = Ep.RestAdapter.extend({
  url: 'api',
  namespace: 'v1'
});
```

**Comment by brandonparsons** [comment]
Thanks!

**Comment by ghempton** [comment]
Going to close since this was fixed. Thanks @c0urg3tt3
