### ISSUE TITLE
model names aren't resolving properly

### ISSUE THREAD

**Issue by rayb** [getoutreach/epf#6]
In a route I need to call  model 'fooModel' rather than 'foo' to gain access to it.  It seems that a nameResolver functionality is missing in the current epf implementation that would address this issue.

**Comment by ghempton** [comment]
This is a pretty bad issue for people just getting started. I will try and fix in epf shortly. Right now, `session.load('post')` will lookup App.PostModel instead of App.Post. In order to fix this in the short term add the following to your application:

``` coffeescript
App = Em.Application.create
  resolver: Ember.DefaultResolver.extend
    resolveModel: (parsedName) ->
      className = Ember.String.classify(parsedName.name)
      factory = Ember.get(parsedName.root, className)
      return factory if factory
```

**Comment by ghempton** [comment]
Should be fixed now. Website will have a new download shortly.

**Comment by ghempton** [comment]
Thanks catching this one @rayb!
