### ISSUE TITLE
How To Debug the Tests

### ISSUE THREAD

**Issue by ginty** [getoutreach/epf#62]
Not really an issue but I don't know where else to ask...

I have a small bug fix I would like to submit and I've added a test for it, however I can't get the test to work properly.

I've never used this testing framework before and I'm not sure how to go about debugging it. I've tried googling but honestly I'm not really sure what I should be searching for.

Could someone give me a pointer as to how to go about setting a breakpoint to inspect and step through the test execution? 

Thanks!

**Comment by ghempton** [comment]
I use [node-inspector](https://github.com/node-inspector/node-inspector) to debug. That allows you to use the chrome dev tools in conjunction with node. Once you have that setup you can just add debugger statements.

Also, feel free to open a PR with your existing work if you want me to take a look.

**Comment by ginty** [comment]
Thanks as always for the quick reply.

I've got that installed now but the bit I don't get is how to run "npm test" within a debuggable node session?

**Comment by ghempton** [comment]
Try `mocha --debug-brk`

**Comment by ginty** [comment]
OK got it now, thanks!

**Comment by ghempton** [comment]
Glad it worked! Being as I'm sure many other people besides yourself might have this issue, is there any possibility you could do a quick addition to `README.md` that details how to get set up?

**Comment by ginty** [comment]
Yep will do
