### ISSUE TITLE
metadata support

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#70]
Does epf support accessing metadata, like this sample payload?

``` json
{
  "meta": 
  {
    "baz": "quux",
    "since": 12159837492
  },
  "foos": { }
}
```

Let say the above payload comes back from

``` javascript
session.query('foo', { search: 'bar' });
```

Can we have the metadata attached to the model array - e.g.

``` javascript
doSomething().then( function(models) {
  // maybe models.meta
  // or models.getMeta();
  // etc
});
```

Or perhaps another reasonable pattern is attaching to the master class - e.g.

``` javascript
App.Foo.meta
App.Foo.getMeta();
// ...
```

Although I'm leaning on the former, or at least some way to distinguish between different `session.query()` calls with different parameters.

Reference: 
- relevant section (best/standard practice?) from `active_model_serializers` [doc](https://github.com/rails-api/active_model_serializers):

> If you would like to add meta information to the outputted JSON, use the `:meta` option:
> 
> ``` ruby
> render json: @posts, serializer: CustomArraySerializer, meta: {total: 10}
> ```
> 
> The above usage of `:meta` will produce the following:
> 
> ``` json
> {
>   "meta": { "total": 10 },
>   "posts": [
>     { "title": "Post 1", "body": "Hello!" },
>     { "title": "Post 2", "body": "Goodbye!" }
>   ]
> }
> ```
- Metadata support in emberjs/data#815 - although I don't think their implementation is neat. For instance, why force a developer to declare meta properties beforehand?

Edit: 
- Found metadata issue opened by @ghempton himself at emberjs/data#124

**Comment by ghempton** [comment]
This currently works in some fashion, but I haven't figured out the final API. Over the next few days I am planning on  baking in a paginated model collection to the framework (and allowing custom collections in general). At that time I will think this through.

**Comment by heartsentwined** [comment]
Alright, thanks in advance!

**Comment by ghempton** [comment]
Metadata on collections should be functioning now.
