### ISSUE TITLE
session.flush() does randomly trigger POST

### ISSUE THREAD

**Issue by sebzincktiz** [getoutreach/epf#72]
<b>Problem:</b>
The call to session.flush() does randomly trigger POST

<b>Source:</b>

```
var self = this,
newUser = self.session.create(App.User,{name:'Seb'}); 

self.session.flush().then(function() { 
    self.get("content").addObject(newUser);
}, function(exception){
    console.error(exception);  
});
```

<b>User definition:</b>

```
App.User = Ep.Model.extend({
    name: Ep.attr('string')    
});
```

**Comment by jasonkriss** [comment]
What exactly do you mean by "session.flush() does randomly trigger POST"? This code should trigger a post to /users. Are you saying it does not?

**Comment by sebzincktiz** [comment]
I mean that sometimes this piece of code trigger a POST request sometimes no. I can't figure out why...

**Comment by ghempton** [comment]
@sebzincktiz can you elaborate on this situation?

**Comment by ghempton** [comment]
Going to close until we can get more information
