### ISSUE TITLE
Relationships Not Updating

### ISSUE THREAD

**Issue by bobjackman** [getoutreach/epf#73]
After a `PUT` request, the server is sending back a response with several updated models (other than the model that was updated/PUT). EPF is successfully updating all the attributes of these "other" models, but it seems that the _relationships_ are not being updated at all. Am I doing something wrong, or is this a bug?

---
### Models

``` javascript
App.SubdivisionModel = Ep.Model.extend({
    assignee:     Ep.belongsTo( 'App.UserModel' )
    parent:       Ep.belongsTo( 'App.AreaModel' ),
    subdivisions: Ep.hasMany( 'App.SubdivisionModel' )
});

App.UserModel = Ep.Model.extend({
    username:  Ep.attr( 'string' ),
    firstName: Ep.attr( 'string' ),
    lastName:  Ep.attr( 'string' ),

    group:       Ep.belongsTo( 'App.GroupModel' ),
    subdivision: Ep.belongsTo( 'App.SubdivisionModel' ),
});
```

---
#### Request

``` javascript
{
  "subdivision_model": {
    "assignee_id": 112,
    "parent_id": 306
  }
}
```
#### Response

``` javascript
{
  "subdivision_models": [
    {
      "id": 308,
      "assignee_id": 112,
      "parent_id": 306,
      "subdivision_ids": []
    }
  ],
  "user_models": [
    {
      "id": 112,
      "username": "xberger",
      "first_name": "Xander",
      "last_name": "Berger",
      "group_id": 201,
      "subdivision_id": 308
    }
  ]
}
```

Note the changes made here:
- User 112 assigned to Subdivision 308
  - You can see both sides of the relationship in the response data

---
#### Request

``` javascript
{
  "subdivision_model": {
    "assignee_id": 112,
    "parent_id": 306
  }
}
```
#### Response

``` javascript
{
  "subdivision_models": [
    {
      "id": 310,
      "assignee_id": 112,
      "parent_id": 306,
      "subdivision_ids": []
    },
    {
      "id": 308,
      "assignee_id": null,
      "parent_id": 306,
      "subdivision_ids": []
    }
  ],
  "user_models": [
    {
      "id": 112,
      "username": "xberger",
      "first_name": "Xander",
      "last_name": "Berger",
      "group_id": 201,
      "subdivision_id": 310
    }
  ]
}
```

Note the changes made here:
- User 112 assigned to Subdivision 310
  - You can see both sides of the relationship in the response data
- Subdivision 308 now shows `null` for its `assignee_id` confirming that the change was made, and that the server is enforcing the 1:1 nature of the relationship.

---

Checking the user shows he is assigned to subdivision 310 (as expected)

``` javascript
App.UserModel.find(112).get( 'subdivision.id' ); // -- yields "310" (yes, a string. not sure if that matters or not)
```

However, if I now check the subdivisions (308 and 310), they _both_ show user 112 as their assignee!

``` javascript
App.SubdivisionModel.find(308).get( 'assignee.id' ); // -- yields "112"
App.SubdivisionModel.find(310).get( 'assignee.id' ); // -- yields "112"
```

To complicate matters (or, possibly, simplify them), this same behavior is noted _regardless_ of whether the server responds with model updates. I can completely remove the "other" models from the server response, and this same issue happens. Responding with the updated data of the "other" models was an attempt to solve this issue, and I was very surprised to see that, even when specifically told by the server to change relationships, EPF isn't doing it.

Again, am I doing something wrong here, or is this a bug?

**Comment by ginty** [comment]
Not sure if it is the root cause here but I had some problems getting relationships to work initially upon migrating from ED, the changes required for things to work well in EPF were:

1) In the relationship declaration you don't use the class name.

``` javascript
// This
App.SubdivisionModel = Ep.Model.extend({
    assignee:     Ep.belongsTo( 'App.UserModel' )
    parent:       Ep.belongsTo( 'App.AreaModel' ),
    subdivisions: Ep.hasMany( 'App.SubdivisionModel' )
});

// Should be changed to this
App.SubdivisionModel = Ep.Model.extend({
    assignee:     Ep.belongsTo( 'userModel' )
    parent:       Ep.belongsTo( 'areaModel' ),
    subdivisions: Ep.hasMany( 'subdivisionModel' )
});
```

2) EPF really likes for the server to respond with a clientId. You will see in your PUT requests that EPF includes a clientId parameter, you should pass this through your server and return it. I think this was the main one that turned relationships from not working at all to working pretty much perfectly for me.

**Comment by bobjackman** [comment]
@ginty thanks for the reply. I've updated my code to use `userModel` instead of `App.userModel`, but that alone, didn't seem to change anything one way or another. As for point #2, it doesn't look like EPF is submitting a clientId param with the request payload. The request payloads shown in the OP are verbatim and complete versions of what EPF is sending. Any other ideas?

**Comment by bobjackman** [comment]
Anyone else have any ideas?

**Comment by ghempton** [comment]
I think this should work if you use instead: `Ep.belongsTo( 'user' )`
