### ISSUE TITLE
While Looking at adminjs I noticed epf was causing some autoruns

### ISSUE THREAD

**Issue by stefanpenner** [getoutreach/epf#77]
specifically the rest adapters ajax

look to ember-data's rest adapter for a solution.
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js#L475-L512

**Comment by stefanpenner** [comment]
This would also allow you to refactor all the `Ember.run`'s in the handlers that consume `this.ajax`

**Comment by ghempton** [comment]
This should be fixed.
