### ISSUE TITLE
Models with numbers not round tripping to the server

### ISSUE THREAD

**Issue by dgdosen** [getoutreach/epf#8]
We've got a simple app with a simple model with a number attribute (age).  When we create a new object, the property with a number attribute is not being sent to the server.

``` javascript
App.Foo = Ep.Model.extend
  name: Ep.attr('string')
  age: Ep.attr('number')
```

In addition, when we query data from the server, We can see the data in the server's json response, but that data does not flow through to the template.

Any ideas?

**Comment by rayb** [comment]
It's not just the number property that is not being sent, but also boolean properties.  When looking at the serialization code on the client it seems that the keys only contain strings and the client id.  boolean and number model properties don't seem to make it into the keys.  For sure none of these boolean or number properties come across in the server create call, but they do show up in the data coming back from the server when you look at the network traffic.

**Comment by ghempton** [comment]
This should definitely work (and does for us). Could you post some more code and the json returned from the server?

**Comment by ghempton** [comment]
Per our in-person conversation, I am closing this issue. Turned out to be a coffeescript compilation issue.
