### ISSUE TITLE
find/load/query by model class

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#83]
This throws an error:

``` javascript
App.__container__.lookup('session:main').find(App.Foo, 1);
```

![screenshot from 2013-08-30 15 25 27](https://f.cloud.github.com/assets/2252978/1055759/834e3d56-1145-11e3-8441-ca02c3a6722e.png)

This doesn't:

``` javascript
App.__container__.lookup('session:main').find('foo', 1);
```

However, the former is called in the static [`modelClass.find()` method](https://github.com/GroupTalent/epf/blob/master/lib/model/model.js#L214), where `this` - referring to the class itself - is passed into `session.find()`. Although epf prefers querying by string key lookup, the latter static support has been officially declared as part of epf in order to maintain compatibility of implicit ember behaviors.

Either the `session.find()` call should be fixed to accept a polymorphic first argument (class or string), or the `modelClass.find()` method should explicitly do a class-to-type conversion, and pass the string to `session.find()`. In the latter case, the docs should be updated to reflect that querying by class would not work.

**Comment by ghempton** [comment]
Hmm `App.__container__.lookup('session:main').find(App.Foo, 1);` should work actually. Most of the session methods check to see if the argument is a string. Not sure what the actual issue is here.

**Comment by heartsentwined** [comment]
Thanks for your reply @ghempton, I'll do some more debugging on my side and see if I can isolate the problem. Just to note, #84 is reported based on observation from my same setup, so there's a chance that it's not epf's problem either...

**Comment by heartsentwined** [comment]
I restarted the server, and it **Just Worked**. Not sure what happened. Sorry for this issue report.

EDIT: No, it doesn't work - see comment below.

**Comment by heartsentwined** [comment]
On a side note, I created a barebones setup to test #84, and the reported behavior is independently observed. So it's not related to this setup.

**Comment by heartsentwined** [comment]
Edit: I take that back. I didn't realize the `ember` version has changed. When I put `1.0.0.rc8` back, the error pops up. `git bisect` gives the same emberjs/ember.js@7c9e714 as the first breaking commit as #84.

**Comment by ghempton** [comment]
Is this still an issue on the latest version of epf? Our app is running off of Ember.js master

**Comment by heartsentwined** [comment]
Issue no longer present with 

```
ember-source 1.0.0
epf-source 0.1.3
```

(gem versions)

**Comment by ghempton** [comment]
I actually just bumped the version and cut another source gem.

**Comment by heartsentwined** [comment]
Thanks! I'll test the new version later.
