### ISSUE TITLE
rc8 breaking adapter pluralization

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#84]
Given

``` coffeescript
Ep.RestAdapter.configure 'plurals',
  foo: 'foo' # force singular
```

This query

``` javascript
App.__container__.lookup('session:main').query('foo');
```

would correctly reach `/foo` in `ember 1.0.0.rc7`, but would reach `/foos` in `ember 1.0.0.rc8`, as if the plural configuration is ignored.

A `git bisect` gives emberjs/ember.js@7c9e714 as the first breaking commit.

**Comment by ghempton** [comment]
Thanks for the bisect. I will get to the bottom of this.

**Comment by ghempton** [comment]
EPF now uses ember-inflector, and the pluralization API has changed to be the same as ED 1.0. Am closing, but please re-open if you still have issues.

**Comment by heartsentwined** [comment]
kudos for `ember-inflector`! I had been using that in my apps for some time, but then I had to keep track of which lib is following it and which isn't...
