### ISSUE TITLE
change in custom transform registration

### ISSUE THREAD

**Issue by heartsentwined** [getoutreach/epf#97]
Another "issue" as a reference for future googlers. If there's a docs site or something like that, I'd be glad to contribute over there :smile:

In `0.1.3`:

``` coffeescript
Em.onLoad 'Ember.Application', (app) ->
  app.initializer
    name: 'registerRawTransform'
    initialize: (container, application) ->
      container.lookup('serializer:main').registerTransform 'raw',
        deserialize: (serialized) -> serialized
        serialize: (deserialized) -> deserialized
```

`0.1.4`:

``` coffeescript
class Ep.RawTransform extends Ep.Transform
  deserialize: (serialized) -> serialized
  serialize: (deserialized) -> deserialized

Em.onLoad 'Ember.Application', (app) ->
  app.initializer
    name: 'registerRawTransform'
    initialize: (container, application) ->
      application.register 'transform:raw', Ep.RawTransform
```

**Comment by ghempton** [comment]
Thanks for posting this! Definitely need more docs.

I think with 0.1.4 you should be able to get away with not having the initializer. Ember's default resolver will automatically check the namespace.

**Comment by heartsentwined** [comment]
I thought [the implementation of `transformFor`](https://github.com/GroupTalent/epf/blob/master/lib/serializer/json_serializer/json_serializer.js#L115) means that I have to register the transform beforehand?

**Comment by ghempton** [comment]
You only have to register it if you break conventions. By default `container.lookup('transform:raw')` will resolve to `Namespace.RawTransform`.

Ah actually as I type this, I see that you added it to the `Ep` namespace rather than your app's namespace. In that case you would have to register it.

**Comment by heartsentwined** [comment]
Oh thanks for the clarification! I'm still wrapping my head over the DI stuff at ember

**Comment by ghempton** [comment]
As an fyi, I have refactored the serialization layer and there is no longer a difference between `serializers` and `transforms`. The only practical application here is that the transform should be renamed to `RawSerializer`. Moreover, since transforms and serializers are now one and the same, you can actually have attributes with model types (e.g. `Ep.attr 'post'`) but I digres....
